[platformio]
default_envs = uno
core_dir = .pio-core

[env:uno]
platform = platformio/atmelavr@5.3.0
board = uno
framework = arduino
lib_deps =
  adafruit/Adafruit SSD1306@2.5.17
  adafruit/Adafruit GFX Library@1.12.6
  adafruit/Adafruit BusIO@1.17.4
